USE [master]
GO

CREATE DATABASE [RepeatableReadData]
USE [RepeatableReadData]
GO

CREATE TABLE [dbo].[Numbers](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[number] [int] NOT NULL,
 CONSTRAINT [PK_Numbers] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
